### ISSUE TITLE
Adapter lässt sich nicht installieren

### ISSUE THREAD

**Issue by souhl** [Codibris/ioBroker.tibberconnect#103]
**Describe the bug**  
Versuche den Adapter über den GitHub Link zu installieren. Doch leider lädt er nicht, sondern bleibt im "Running command" Fenster stehen.

**To Reproduce**  
1. Go to GitHib Icon
2. Paste Link
3. Install

**Expected behavior**  

**Screenshots & Logfiles**  
$ iobroker url https://github.com/Codibris/ioBroker.tibberconnect --host smarthome --debug
install Codibris/ioBroker.tibberconnect#9afa849891c6184f7314e1ed174b728ed4d4d757
NPM version: 6.14.17
Installing Codibris/ioBroker.tibberconnect#9afa849891c6184f7314e1ed174b728ed4d4d757... (System call)
<img width="918" alt="Screenshot 2022-11-21 at 15 35 06" src="https://user-images.githubusercontent.com/5879835/203114651-a8b5ec17-6bc5-4310-ae80-954b4c2a345d.png">
<img width="1017" alt="Screenshot 2022-11-21 at 15 34 56" src="https://user-images.githubusercontent.com/5879835/203114666-babe8c99-ce92-4a49-a4c8-8ed887886377.png">

**Versions:**  
 - Adapter version: 0.07
 - JS-Controller version: 4.0.23 
 - Node.js: v14.20.0
 - Operating system: ubuntu

**Comment by crusader85** [comment]
gleiches bei mir

**Comment by crusader85** [comment]
> gleiches bei mir

OK, mit manueller Adapterinstallation hat es dann geklappt

iobroker add tibberconnect

**Comment by souhl** [comment]
Damit ging es bei mir auch. Aber scheint da noch irgendwo noch zu haken..

**Comment by weindler** [comment]
Also bei mir lief die Installation durch

**Comment by souhl** [comment]
Ich denke, den können wir schließen.
