### ISSUE TITLE
Einladungscode

### ISSUE THREAD

**Issue by volkerrichert** [Codibris/ioBroker.tibberconnect#116]
Hey Codibris,

ich wollte zu tibber wechseln. Neben coding skills könnte ich dich / den Adapter auch über den Einladungscode unterstützen. Wenn du den veröffentlichst, dann kann man den nutzen. Und kalr, ich habe auch was davon. ;-)

**Comment by Codibris** [comment]
https://invite.tibber.com/hgg53izs

Hier der Link. Ich werde das mal im Forum in der Readme noch ergänzen. Danke für den Hinweis.
