### ISSUE TITLE
No price data downloaded

### ISSUE THREAD

**Issue by Waldmensch1** [Codibris/ioBroker.tibberconnect#146]
Hi,

I installed the Adapter and entered the API key from Tibber. It looks that the connection works as base data get downloaded. Unfortunately it seems that the download of price data fails. Adapter runs since 24 hrs now and I see requests in log regularily, but they always seems to be empty. I have no tibber-pulse or else installed.

![image](https://user-images.githubusercontent.com/57328533/212620268-878f2186-1946-4b93-bf77-33b7f2fec286.png)

![image](https://user-images.githubusercontent.com/57328533/212620712-fee2a4d5-4bd0-4dce-a210-e7181607e3ea.png)

**Comment by Waldmensch1** [comment]
Strange thing is the response in developer explorer. What have to be done to get a subscription? Is it dependend on an energy delivery contract? 

"currentSubscription": null



```
{
  viewer {
    homes {
      currentSubscription{
        priceInfo{
          current{
            total
            energy
            tax
            startsAt
          }
          today {
            total
            energy
            tax
            startsAt
          }
          tomorrow {
            total
            energy
            tax
            startsAt
          }
        }
      }
    }
  }
}

```

```
{
  "data": {
    "viewer": {
      "homes": [
        {
          "currentSubscription": null
        }
      ]
    }
  }
}
```

**Comment by volkerrichert** [comment]
Yes, you need a contract to get data. You can use the demo key, but it will return (SEK)

**Comment by Waldmensch1** [comment]
okay, can be closed then
