### ISSUE TITLE
Adapter zum Anbietervergleich nutzbar? 

### ISSUE THREAD

**Issue by aDabbelju** [Codibris/ioBroker.tibberconnect#148]
Kann dieser Adapter auch genutzt werden, we. Man keinen Liefervertrag bei tibber besitzt? Ich würde gerne meinen IST-Dtand mit dem von tibber vergleichen, um die Kosten zu vergleichen. Ist dies möglich? Schließlich benötige ich ja auch einen API-Token.

Danke & Grüße

**Comment by tugsi** [comment]
Nein dies ist nicht möglich. 
Wie Du schon schreibst, Du brauchst ein API-Token.
Es gibt einen Demo-Token, aber der ist nicht auf Deutschland bezogen, ausserdem hast Du einen unterschiedlichen Arbeitsstromgrundpreis, je nachdem wo Du wohnst (Netzentgelte etc.). 
Ich habe irgendwo gelesen, dass Tibber sowas plant, es öffentlich zu machen, aber wer weiß wann...
Alternativ kannst Du mal den Adapter von Awattar anschauen, die bieten einen öffentlichen Preis an, im Adapter kannst den Grundarbeitspreis anpassen, denn kannst ja vo oder Tibberseite rausfinden, wenn dir mal berechnen lässt. Ist dann zwar immer noch nicht ganz exakt, weil Steuern, aber man hat einen recht genauen Wert.
Andersherum, wenn ich sehe, dass die in den letzen Wochen/Monaten nie über 40Cent/kWh kamen, da brauche ich nicht vergleichen ;) 
Wie gesagt, schau da mal bei Awattar rein.
Gruß

**Comment by aDabbelju** [comment]
Das wäre auch zu schön gewesen. Ich beobachte mal die Preise bei tibber und werde eventuell später dort hinwechseln, wenn der Preis für mich steigt. Trotzdem vielen Dank für deine Antwort.

Grüße
