### ISSUE TITLE
Instanz bleibt auf gelb

### ISSUE THREAD

**Issue by Michaelnorge** [Codibris/ioBroker.tibberconnect#82]
Der Adapter funktioniert super, sogar der Live-Verbrauch wird ausgegeben!
Allerdings steht die Instanz dauerhaft auf "gelb", obwohl der Adapter zu arbeiten scheint.

![image](https://user-images.githubusercontent.com/42386692/198621821-e157ce61-602e-41fd-a250-91bbca6dcbd1.png)

Danke für die tolle Arbeit! 
Wird hier noch weiterentwickelt?

**Comment by Codibris** [comment]
Ich schaue mir das an. Der Status wird bisher noch nicht gesetzt. Da muss ich definitiv noch mal ran.
